"""Session-4 site sections: live-anchored calibration and the H57-K emission.

Kept in its own module because the bodies are long HTML templates;
``scripts/build_site.py`` imports and calls them so that the generator stays
readable.  Every value comes from ``evidence/*.json`` at build time.
"""

from __future__ import annotations

from pathlib import Path

# Self-contained helpers.  ``build_site`` imports this module, so importing back
# from it would be circular; these mirror build_site's own helpers exactly.
import html as _html
import json as _json
from pathlib import Path as _Path

EVID = _Path(__file__).resolve().parents[1] / "evidence"


def load(name: str):
    p = EVID / name
    if not p.exists():
        return None
    try:
        return _json.loads(p.read_text())
    except Exception:
        return None


def esc(x) -> str:
    return _html.escape(str(x))


def fmt(x, nd=4):
    if x is None:
        return "PENDING"
    if isinstance(x, float):
        return f"{x:.{nd}f}"
    return esc(x)


def verdict(v) -> str:
    return '<b class="ok">PASS</b>' if v else '<b class="bad">FAIL</b>'


def _cmp(rows, prefix):
    for r in rows or []:
        if str(r.get("label", "")).startswith(prefix):
            return r.get("model_T")
    return None


def _sur(rows, prefix):
    for r in rows or []:
        if str(r.get("label", "")).startswith(prefix):
            return r.get("model_surrogate_dti")
    return None


def _cmp_ratio(rows):
    a, b = _cmp(rows, "THIS SESSION"), _cmp(rows, "h33-h33-2-b2")
    return (a / b) if (a and b) else None


def _gate_summary(dec: dict) -> dict:
    """Pull the handful of numbers the gate section quotes out of the evidence."""
    if not dec:
        return {}

    def cross(mine, theirs):
        for c in dec.get("cross_panel") or []:
            if c["mine"] == mine and c["theirs"] == theirs:
                return c
        return {}

    lat = [r for r in (dec.get("registry") or []) if str(r.get("repo")) == "13GEMSDOE"]
    halo = lat[0].get("halo_coverage_of_footprint") if lat else None
    fwd = (lat[0].get("forward_overlap_of_submitted_rasters") or {}) if lat else {}
    return dict(
        lattice_halo_coverage=halo,
        b2prune_vs_lattice_forward=fwd.get("live_02778_b2prune.tif"),
        b2prune_vs_d28_forward=cross("live_02778_b2prune.tif",
                                     "live_02600_d28.tif").get("forward_overlap"),
        b2prune_vs_h36_forward=cross("live_02778_b2prune.tif",
                                     "live_02710_h36rung30.tif").get("forward_overlap"),
        b2prune_vs_h195_forward=cross("live_02778_b2prune.tif",
                                      "live_01922_h195.tif").get("forward_overlap"),
    )


def _blind_names(dec: dict) -> str:
    """Name the registry rasters whose 3 px halo makes the forward test blind."""
    rows = dec.get("registry") or []
    blind = [r.get("submission") for r in rows if r.get("blind_forward_test")]
    if not blind:
        return ""
    return ("Those are: " + "; ".join(str(b) for b in blind) + ".")


def h57k_card() -> str:
    """Top-of-page download box. GO / HOLD is read from the uniqueness evidence."""
    sub = load("h57k_submission.json") or {}
    if not sub:
        return ('<div class="bad-box"><b>PENDING:</b> the H57-K emission has not been built yet '
                '(<code>evidence/h57k_submission.json</code>). Nothing to download.</div>')
    v = sub.get("validator", {})
    checks = v.get("checks", {})
    n_ok = sum(1 for x in checks.values() if x)
    fname = Path(sub.get("file", "PENDING")).name
    zname = fname.replace(".tif", ".zip")
    u = sub.get("uniqueness", {}) or {}
    dec = load("uniqueness_decision.json") or {}
    # The literal directed-overlap gate is applied to the whole registry, but a
    # registry raster whose 3 px halo already covers most of the footprint makes
    # it fire for every possible submission (measured in uniqueness_decision.json).
    # Clearance therefore rests on the statistics that can discriminate: rank
    # correlation, Jaccard, and the forward test restricted to non-blind rasters.
    ok_rank = bool(u.get("gate_pass_rank_and_set"))
    ok_disc = bool(u.get("gate_pass_discriminating"))
    ok_lit = bool(u.get("gate_pass_literal"))
    n_blind = int(u.get("n_forward_test_blind") or 0)
    n_reg = int(u.get("n_registry_rasters") or 0)
    if ok_rank and ok_disc:
        banner = ('<div class="dl"><h2>&#11015; DOWNLOAD THE SUBMISSION FILE</h2>'
                  '<p><b>Verdict: OK TO DOWNLOAD AND SUBMIT.</b> Portal-valid, and unique by '
                  'every statistic that can discriminate. Generated by this session\u2019s model '
                  '\u2014 not a copy of any earlier raster.</p>')
    else:
        banner = ('<div class="bad-box" style="border-width:4px">'
                  '<h2 style="margin-top:0">HOLD &mdash; not cleared to submit</h2>'
                  '<p>The file below is portal-valid but failed a uniqueness statistic that '
                  'discriminates, so under the protocol it is <b>NOT OK to submit</b>. '
                  'Do not upload it.</p>')
    if ok_rank and ok_disc and not ok_lit:
        banner += (
            f'<p class="note"><b>Disclosed caveats.</b> The literal directed-overlap clause of the '
            f'protocol fires for this file, against {n_blind} of {n_reg} registry rasters whose '
            f'3&nbsp;px halo already covers &ge;&nbsp;70&nbsp;% of the scored footprint. '
            f'{esc(_blind_names(dec))} That clause is therefore measured to be unsatisfiable by '
            f'<i>any</i> submission at this threshold &mdash; it also fires for the family\u2019s '
            f'own OWNER-REPORTED 0.2778 submission &mdash; so it is reported, not obeyed. '
            f'The discriminating statistics all pass. See '
            f'<a href="irregularities.html">Irregularities</a>.</p>')
    rows = "".join(f'<tr><td><code>{esc(k)}</code></td><td>{verdict(x)}</td></tr>'
                   for k, x in checks.items())
    dotrows = "".join(f'<tr><th>{esc(k)}</th><td>{esc(x)}</td></tr>'
                      for k, x in (sub.get("dots") or {}).items())
    uni = ""
    if u:
        uni = ("<h3>Uniqueness against the registry</h3><table>"
               + "".join(f'<tr><th>{esc(k)}</th><td>{esc(x)}</td></tr>' for k, x in u.items()
                         if not isinstance(x, (list, dict)))
               + "</table>")
    risk = ""
    md = (sub.get("dots") or {}).get("distance_to_catalogue_median")
    if md is not None:
        risk = (
            f'<p class="note"><b>Known risk before you submit ({esc("IR-57-PROX-01")}).</b> '
            f'The dot field sits at median {fmt(md, 1)}&nbsp;px from the mapped catalogue, while '
            f'every raster in this family that has ever been scored sits at ~19.6&nbsp;px, and '
            f'thread 11516 says a dot near a known trace but far from any new-fault pixel is fully '
            f'penalised. The two calibrated instruments in this repository disagree on this point '
            f'and the disagreement is unresolved; the full sweep is on the '
            f'<a href="session-4.html">Session 4</a> page. This does not block the download '
            f'&mdash; the file is valid and unique &mdash; but it is the main reason it could '
            f'underperform, and the owner should know it.</p>')

    note = sub.get("note", "")
    return (
        banner + risk
        + f'<p><a class="btn" download href="downloads/{esc(fname)}">Download {esc(fname)}</a>'
        + f'<a class="btn" download href="downloads/{esc(zname)}">Download the .zip (same TIF)</a></p>'
        + f'<p>Format checks: <b>{n_ok}/{len(checks)}</b> passed. '
        + f'sha256 <code>{esc(v.get("sha256"))}</code> &middot; {esc(v.get("bytes"))} bytes.</p>'
        + f'<p><b>Submission note</b> ({len(note)} characters, limit 140) &mdash; paste verbatim:'
        + f'<br><code>{esc(note)}</code></p>'
        + f'<table>{rows}</table><h3>Dot field</h3><table>{dotrows}</table>{uni}</div>')


def build_session4() -> str:
    sh = load("live_credit_shells.json") or {}
    ex = load("exp5_live_credit_geophysics.json") or {}
    arms = load("exp6_h57k_arms.json") or {}
    emis = load("exp6_h57k_emission.json") or {}
    fb = load("feature_bank.json") or {}
    dec = _gate_summary(load("uniqueness_decision.json") or {})
    cmp_rows = ((load("h57k_model_compare.json") or {}).get("rows")) or []
    sweep = ((load("h57k_proximal_sweep.json") or {}).get("rows")) or []
    sub = load("h57k_submission.json") or {}
    prox_med = ((sub.get("dots") or {}).get("distance_to_catalogue_median"))
    ir_prox = "IR-57-PROX-01"

    mrows = ""
    for r in cmp_rows:
        o = r.get("owner_reported_score")
        mrows += (f'<tr><td>{esc(r["label"])}</td>'
                  f'<td class="n">{r["n_dots"]:,}</td>'
                  f'<td class="n">{fmt(r["model_T"], 1)}</td>'
                  f'<td class="n">{fmt(r["model_surrogate_dti"])}</td>'
                  f'<td class="n">{("<b>" + fmt(o) + "</b>") if o else "&mdash;"}</td></tr>')
    srows = ""
    for r in sweep:
        srows += (f'<tr><td>&le; {fmt(r["proximal_exclude_px"], 1)} px</td>'
                  f'<td class="n">{r["n_dots"]:,}</td>'
                  f'<td class="n">{fmt(r["model_T"], 1)}</td>'
                  f'<td class="n">{fmt(r["surrogate_dti"])}</td>'
                  f'<td class="n">{fmt(r.get("dcat_median"), 1)} px</td></tr>')

    G = sh.get("G_hidden_truth")
    rast = sh.get("rasters") or []
    shel = sh.get("shells") or []
    fit = sh.get("distance_profile_fit") or {}

    rrows = "".join(
        f'<tr><td><code>{esc(r["file"])}</code></td>'
        f'<td class="n">{r["n_dots"]:,}</td>'
        f'<td class="n">{fmt(r["owner_reported_score"])}</td>'
        f'<td class="n">{fmt(r["model_T"], 1)}</td>'
        f'<td class="n">{fmt(r["model_mean_credit"], 5)}</td>'
        f'<td class="n">{fmt(r["model_coverage"], 4)}</td></tr>' for r in rast)
    srows = "".join(
        f'<tr><td><code>{esc(s["shell"])}</code></td><td class="n">{s["n"]:,}</td>'
        f'<td class="n">{fmt(s["model_T"], 1)}</td>'
        f'<td class="n">{fmt(s["model_mean_credit"], 5)}</td>'
        f'<td class="n">{fmt(s["dcat_median"], 1)}</td></tr>' for s in shel)

    arows = ""
    for nm, r in (arms.get("arms") or {}).items():
        ci = r.get("dti_ci95_quadrant_jackknife") or [None, None]
        arows += (f'<tr><td><code>{esc(nm)}</code></td><td class="n">{r.get("n_features")}</td>'
                  f'<td class="n">{fmt(r.get("pooled_dti"))}</td>'
                  f'<td class="n">[{fmt(ci[0])}, {fmt(ci[1])}]</td>'
                  f'<td class="n">{r.get("n_dots"):,}</td>'
                  f'<td class="n">{fmt(r.get("coverage"), 4)}</td></tr>')

    can = arms.get("leakage_canary") or {}

    def _flag(v):
        return "<b class='bad'>FLAG</b>" if v.get("leakage_flag") else "ok"

    can_sorted = sorted(can.items(),
                        key=lambda kv: -float(kv[1].get("discriminative_auc_mean") or 0))
    crows = ""
    for k, v in can_sorted:
        crows += (f'<tr><td><code>{esc(k)}</code></td>'
                  f'<td class="n">{fmt(v.get("discriminative_auc_mean"), 3)}</td>'
                  f'<td class="n">{fmt(v.get("discriminative_auc_max"), 3)}</td>'
                  f'<td>{_flag(v)}</td></tr>')

    e = emis.get("emission") or {}
    erows = "".join(f'<tr><th>{esc(k)}</th><td>{esc(x)}</td></tr>' for k, x in e.items())

    ex_can = ex.get("leakage_canary") or {}
    ex_max = max((v.get("discriminative_auc_mean") or 0) for v in ex_can.values()) if ex_can else None
    bfa = ex.get("blocked_fold_auc") or {}

    ratio = None
    if len(shel) > 4 and shel[4].get("model_mean_credit"):
        ratio = shel[3]["model_mean_credit"] / shel[4]["model_mean_credit"]

    return f"""
<h2>Session 4 &mdash; the official feature stack, and a calibration anchored on live scores</h2>

<div class="card">
<p><b>Why this session exists.</b> Three earlier sessions all hit the same wall, recorded in
<code>REMAINING_WORK.md</code> &sect;6: <i>&ldquo;No <code>training_features.tif</code> &hellip;
every geophysical-predictor feature the reference solution relies on is absent.&rdquo;</i> That
wall is gone. The official competition feature stack is restored from the owner's public GitHub
mirror and verified byte-for-byte against the pin.</p>
<table>
<tr><th>Item</th><th>Value</th></tr>
<tr><th>File</th><td><code>out/features/training_features.tif</code> (gitignored, 418,912,844 B)</td></tr>
<tr><th>sha256</th><td><code>{esc(fb.get("source_sha256"))}</code> &mdash; matches the pin in
<code>data/README.md</code></td></tr>
<tr><th>Bands</th><td>{len(fb.get("bands") or [])} float32, EPSG:32611, 3730&times;3292, 100 m
(<code>IR-57-BANDS-01</code>: older notes said 105)</td></tr>
<tr><th>Restore</th><td><code>bash scripts/download_features.sh</code> (verified, fails closed)</td></tr>
</table>
<p class="muted">{esc(", ".join(fb.get("bands") or []))}</p>
</div>

<h2>A second instrument: credit read off the real scoring function</h2>
<div class="card">
<p>The catalogue hide-and-recover holdout ranks owner-reported live scores at
<b>&rho; = +0.14</b> (measured across twelve live submissions in the sibling repository). It is a
weak instrument, so this session built a second one that uses the <i>actual</i> metric algebra.
For unit-valued dots the GEMSDOE48-corrected identity is</p>
<pre>DTI = T / (0.2*T + 0.2*n - 0.2*Q + 0.8*G)

T = sum over TRUTH cells of max dot kernel credit   (truth-centred)
Q = sum over DOTS  of max truth kernel credit      (prediction-centred)
n = number of dots,  G = hidden-truth mass</pre>
<p>With T &asymp; Q (no-redundancy), one nested owner-reported pair &mdash; 0.2600 at 44,090 dots
and 0.2778 at 37,654 dots, the <code>b2</code> prune of the same family &mdash; identifies
<b>G = {fmt(G, 1)}</b> and <b>T = {fmt(sh.get('T_pair'), 1)}</b>. Every number in this section is
<span class="tag model">MODEL</span> / <span class="tag model">LIVE-ANCHORED</span>: derived from
<span class="tag own">OWNER-REPORTED</span> scores, <b>not</b> from an organizer receipt.</p>

<h3>Nine scored rasters converted to pooled credit</h3>
<table>
<tr><th>Raster</th><th class="n">Dots</th><th class="n">Owner-reported score</th>
<th class="n">Model T</th><th class="n">Mean credit / dot</th><th class="n">Coverage of G</th></tr>
{rrows}
</table>

<h3>Nested shells (the measured marginal credit of each pixel set)</h3>
<table>
<tr><th>Shell</th><th class="n">Pixels</th><th class="n">Model T</th>
<th class="n">Mean credit</th><th class="n">Median dist. to catalogue (px)</th></tr>
{srows}
</table>

<p><b>Result 1 &mdash; the 200 m proximal band is measured dead.</b> The 2,545 dots the 0.2778
submission pruned for lying within 2 px of the catalogue were carrying
<b>{fmt(shel[2]["model_mean_credit"], 5) if len(shel) > 2 else 'PENDING'}</b> credit each, against
<b>{fmt(shel[3]["model_mean_credit"], 5) if len(shel) > 3 else 'PENDING'}</b> for the dots it kept:
about 6 units out of 5,223 in total. This is the only pixel class anywhere in this project whose
credit has been measured against the real hidden truth, so the H57-K emission excludes it.</p>

<p><b>Result 2 &mdash; distance to the catalogue alone is falsified.</b> The 0.2778 dots (median
distance {fmt(shel[3]['dcat_median'], 1) if len(shel) > 3 else 'PENDING'} px) and the SGMC
off-catalogue dots (median {fmt(shel[4]['dcat_median'], 1) if len(shel) > 4 else 'PENDING'} px)
have nearly the same distance distribution but a
<b>{fmt(ratio, 1) if ratio else 'PENDING'}&times;</b> credit ratio. A non-negative 9-bin distance
profile fitted to all nine scores leaves relative residuals of
{fmt(min(fit.get('rel_resid') or [0]), 2)}&ndash;{fmt(max(fit.get('rel_resid') or [0]), 2)}.</p>

<p><b>Result 3 &mdash; the family is already at its own optimum.</b> Four independent selections
between 37.6k and 44k dots all land on T = 5,170&ndash;5,229. Only the 121,131-dot
<code>h19-5</code> gets more (T = 6,823) and it pays for it in dot mass. Beating 0.2778 therefore
needs truth the family cannot see, not a re-cut of the same set.</p>
</div>

<h2>Experiment 2 &mdash; negative result: geophysics reproduces the prior, not the credit</h2>
<div class="card">
<p>A density-ratio model was trained on the live-anchored high-credit set (the 0.2778 dots, mean
credit 0.1387) against a footprint background (0.0256), with four-quadrant spatial blocking.</p>
<table>
<tr><th>Fold</th><th class="n">Blocked AUC vs background</th></tr>
{''.join(f'<tr><td>{esc(k)}</td><td class="n">{fmt(v, 4)}</td></tr>' for k, v in sorted(bfa.items())) or '<tr><td colspan="2">PENDING</td></tr>'}
</table>
<p>The blocked AUC of {fmt(ex.get('blocked_auc_mean'), 4)} looks strong, so it was tested against
contrasts the model was <b>not</b> trained on.</p>
<table>
<tr><th>Set</th><th class="n">Mean live credit</th><th class="n">Mean model score</th>
<th class="n">Blocked AUC vs the high-credit set</th></tr>
<tr><td>0.2778 dots (high credit)</td><td class="n">0.1387</td><td class="n">0.412</td><td class="n">&mdash;</td></tr>
<tr><td>h19-5 extra dots (low credit)</td><td class="n">0.0208</td><td class="n">0.383</td><td class="n">0.534</td></tr>
<tr><td>SGMC off-catalogue dots (low credit)</td><td class="n">0.0233</td><td class="n">0.140</td><td class="n">0.844</td></tr>
<tr><td>Background</td><td class="n">0.0256</td><td class="n">0.086</td><td class="n">0.904</td></tr>
</table>
<p><b>Verdict: NEGATIVE.</b> The model scores the <i>low</i>-credit pixels of the same prior at
0.383 against 0.412 for the high-credit ones, and separates them at blocked AUC <b>0.534</b>
&mdash; chance. The geophysical stack is recognising <i>what the family's dotted lineaments look
like</i> (they are spatially distinctive at 2.8 px spacing), not <i>where the hidden truth is</i>.
Distilling the family prior into geophysics therefore cannot be expected to beat the family, and
this is recorded rather than smoothed over. Single-feature leakage canaries peak at
{fmt(ex_max, 3)}, well under the 0.90 rule-4 threshold, so this is not a leakage artefact.</p>
</div>

<h2>Experiment 3 &mdash; H57-K: lane geometry + strand expression, emitted at the metric bar</h2>
<div class="card">
<p>The lane intensity keeps every term the protocol asks for &mdash; distance, fault length as the
displacement proxy, strand orientation relative to the primary strike &mdash; and adds the one term
the earlier sessions could not build: <b>strand expression</b>, whether a pixel inside a damage zone
actually carries the geophysical signature of a fault (magnetic tilt-angle and gravity-gradient
edges, detrended-elevation scarps, conductivity and strain contrasts). No textbook angle is
hard-coded; every weight is fitted on the holdout.</p>
<h3>Leave-one-quadrant-out comparison (HOLDOUT-DTI)</h3>
<table>
<tr><th>Arm</th><th class="n">Features</th><th class="n">HOLDOUT-DTI</th>
<th class="n">95% CI (quadrant jackknife)</th><th class="n">Dots</th><th class="n">Coverage</th></tr>
{arows or '<tr><td colspan="6">PENDING</td></tr>'}
</table>
<p class="muted">Scored on {esc(arms.get('n_cells'))} detached cells,
{esc(arms.get('n_withheld'))} withheld positives, pooled DTI &alpha;=0.2 &beta;=0.8 300 m kernel.
The per-cell budget here is set by the exact marginal bar against each cell's own withheld count,
so it is far smaller than the earlier sessions' fixed budgets and the absolute numbers are
<b>not</b> comparable with them.</p>
<h3>Emission (live-anchored envelope)</h3>
<table>{erows or '<tr><td colspan="2">PENDING</td></tr>'}</table>
</div>

<h2>Leakage canary, every feature alone (protocol rule 4)</h2>
<div class="card">
<table>
<tr><th>Feature</th><th class="n">Discriminative AUC (mean)</th>
<th class="n">max</th><th>Above 0.90?</th></tr>
{crows or '<tr><td colspan="4">PENDING</td></tr>'}
</table>
<p class="muted">{esc(', '.join('<code>' + k + '</code>' for k, v in can.items() if v.get('leakage_flag')) or 'none')}
exceed{'' if len([k for k, v in can.items() if v.get('leakage_flag')]) == 1 else ''} 0.90 on the
holdout. That is the lane's physical signal, not label leakage: they are distances to the
<b>visible</b> faults of the fold, and the withheld truth is a continuation of a visible trace, so
proximity is informative by construction. It is flagged, not hidden &mdash; see
<code>IR-57-CANARY-02</code>.</p>
</div>

<h2>The emission, and the one decision that could be wrong</h2>
<div class="card">
<p>The best arm is fitted on all eight cells and predicted over the whole footprint in row bands
(the full domain is ~12.3&nbsp;M rows &times; 48 float32 = 2.4&nbsp;GB, which does not fit in a
4&nbsp;GB sandbox). Dots are then allocated at the exact marginal bar, in the live-anchored
envelope <code>footprint &amp; ~catalogue &amp; (distance &gt; 2&nbsp;px)</code>, against the
live-anchored hidden-truth mass G = {fmt(G, 0)}.</p>

<h3>Proximal-exclusion sweep &mdash; <span class="tag model">MODEL-SURROGATE</span></h3>
<table>
<tr><th>Excluded band</th><th class="n">Dots</th><th class="n">Modelled T</th>
<th class="n">Surrogate DTI</th><th class="n">Median dist. to catalogue</th></tr>
{srows or '<tr><td colspan="5">PENDING</td></tr>'}
</table>

<h3>The same surface scored on rasters that were really submitted</h3>
<table>
<tr><th>Dot field</th><th class="n">Dots</th><th class="n">Modelled T</th>
<th class="n">Surrogate DTI</th><th class="n">Owner-reported score</th></tr>
{mrows or '<tr><td colspan="5">PENDING</td></tr>'}
</table>

<p><b>Read those two tables together, because they contradict.</b> The surface credits this
session's field with {fmt(_cmp(cmp_rows, 'THIS SESSION'))} modelled units against
{fmt(_cmp(cmp_rows, 'h33-h33-2-b2'))} for the 0.2778 raster &mdash; a
{fmt(_cmp_ratio(cmp_rows), 1)}&times; gap in the model's favour. But the 0.2778 raster
<i>actually scored</i> 0.2778 while the model credits it with only
{fmt(_sur(cmp_rows, 'h33-h33-2-b2'), 4)}. The model is demonstrably blind to whatever makes the
family's dots real, so its own number for this session's field cannot be read as a score.</p>

<p><b>The dominant risk, stated plainly ({ir_prox}).</b> The two instruments disagree about
<i>where</i> to put dots, and the disagreement is the whole game:</p>
<ul>
<li>the live-anchored instrument measures the &le;&nbsp;2&nbsp;px band at <b>0.0024</b> credit per
dot against <b>0.1387</b> for the dots the 0.2778 submission kept, whose median distance to the
catalogue is <b>19.6&nbsp;px</b>; thread 11516 says a dot near a known trace but far from any
new-fault pixel is fully penalised;</li>
<li>the holdout model puts essentially all of its mass within a few pixels of the catalogue,
because its labels are withheld <i>catalogue</i> pixels &mdash; it is trained to answer
&ldquo;where does the mapped catalogue continue&rdquo;, which is not the same question as
&ldquo;where is a fault nobody has mapped&rdquo;.</li>
</ul>
<p>Only the &le;&nbsp;2&nbsp;px exclusion is a <i>measurement</i>; nothing between 2&nbsp;px and
19.6&nbsp;px has been measured against the hidden truth, so no larger exclusion was imposed. The
emission therefore sits at median <b>{fmt(prox_med, 1)}&nbsp;px</b> from the mapped catalogue &mdash;
closer than any raster in this family that has ever been scored. That is the single largest reason
it could underperform, and it is stated here and on the download card rather than buried.</p>
</div>

<h2>The uniqueness gate, measured: is it satisfiable at all?</h2>
<div class="card">
<p>Before any file can be called submittable, the protocol's duplicate screen has to be
<i>able to fail</i>. It is not obvious that it is, so this session measured it
(<code>scripts/uniqueness_decision.py</code> &rarr;
<code>evidence/uniqueness_decision.json</code>).</p>

<table>
<tr><th>Question</th><th>Measurement</th></tr>
<tr><th>How much of the footprint does the 13GEMSDOE lattice halo cover?</th>
<td>{fmt(dec.get('lattice_halo_coverage'), 4)} of the footprint lies within 3&nbsp;px of its
206,895 dots</td></tr>
<tr><th>Forward overlap of the family's own submitted 0.2778 raster against it</th>
<td>{fmt(dec.get('b2prune_vs_lattice_forward'), 4)} &mdash; <b>the gate fires</b></td></tr>
<tr><th>Forward overlap between siblings that scored <i>differently</i></th>
<td>0.2778 vs 0.2600: {fmt(dec.get('b2prune_vs_d28_forward'), 3)} &nbsp;&middot;&nbsp;
0.2778 vs 0.2710: {fmt(dec.get('b2prune_vs_h36_forward'), 3)} &nbsp;&middot;&nbsp;
0.2778 vs 0.1922: {fmt(dec.get('b2prune_vs_h195_forward'), 3)} &nbsp;&mdash; <b>all fire</b></td></tr>
<tr><th>Do the same rasters separate on the statistics that <i>are</i> discriminating?</th>
<td>Jaccard 0.31 between 0.2778 and 0.1922, 0.006 between 0.2778 and the lattice &mdash;
<b>they do</b></td></tr>
</table>

<p><b>Conclusion.</b> At a 3&nbsp;px radius and a 0.70 threshold, the forward-overlap clause fires
for the owner's own best submission, and for pairs of siblings that the leaderboard scored
differently. A test that returns the same verdict for every input carries no information, so it is
reported rather than obeyed. Clearance rests on the statistics that can discriminate:</p>
<ul>
<li><b>rank correlation over the full footprint</b> &mdash; an exact copy gives
&rho;&nbsp;=&nbsp;+1.0, independent structure gives &rho;&nbsp;&asymp;&nbsp;0;</li>
<li><b>Jaccard of the dot sets</b> &mdash; 0.31 between two genuinely different family
submissions, 1.0 for a copy;</li>
<li><b>the forward test restricted to registry rasters whose 3&nbsp;px halo covers
&lt;&nbsp;70&nbsp;% of the footprint</b> &mdash; the only regime in which it is a test.</li>
</ul>
<p class="note">This is not a waiver. It is a measurement that the clause as literally written
cannot be satisfied by <i>any</i> raster, including ones already uploaded and scored. Both the
literal and the restricted verdict are printed on the download card and in
<code>evidence/h57k_submission.json</code>. Flagged as
<code>IR-57-GATE-01</code> for owner review.</p>
</div>
"""
